image: clojure:lein-2.7.0

variables:
  DATABASE_URL: "postgresql://memento:testdb@postgres:5432/memento_test"

before_script:
  - apt-get update -y
  - lein deps


test:
  stage: test
  services:
    - postgres:latest
  script:
  - apt-get install postgresql-client -y
  - psql -h postgres -U postgres < db-setup.sql
  - echo $DATABASE_URL
  - lein with-profile test run migrate
  - lein test

uberjar:
  stage: build
  script:
  - export LEIN_SNAPSHOTS_IN_RELEASE=true
  - lein uberjar
  artifacts:
    paths:
    - target/uberjar/memento.jar
  only:
  - master

production:
  stage: deploy
  script:
  - export LEIN_SNAPSHOTS_IN_RELEASE=true
  - lein uberjar
  - HEROKU_API_KEY=$HEROKU_PRODUCTION_API_KEY lein heroku deploy
  artifacts:
    paths:
    - target/uberjar/memento.jar
  only:
  - tags
