image: clojure:lein-2.7.0

variables:
  DATABASE_URL: "postgresql://memento:testdb@postgres:5432/memento_test"

cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
  - /root/.m2/repository

before_script:
  - export LEIN_SNAPSHOTS_IN_RELEASE=true

stages:
  - test
  - build
  - deploy

test:
  stage: test
  services:
    - postgres:latest
  script:
  # Comment to trigger a re-run
  - ls -la /root/
  - apt-get update -y
  - apt-get install postgresql-client -y
  - psql -h postgres -U postgres < db-setup.sql
  - echo $DATABASE_URL
  - lein with-profile test run migrate
  - lein cloverage --codecov
  - ls -la /root/.m2/
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json -t $CODECOV_KEY
  - ls -la /root/.m2/repository

uberjar:
  stage: build
  script:
  - lein uberjar
  artifacts:
    paths:
    - target/uberjar/memento.jar
  only:
  - tags

production:
  stage: deploy
  script:
  - lein uberjar
  - HEROKU_API_KEY=$HEROKU_PRODUCTION_API_KEY lein heroku deploy
  artifacts:
    paths:
    - target/uberjar/memento.jar
  only:
  - master
