coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 30%    # Still adding untested experiments
        threshold: 10%

ignore:
  - "env/.*"   # Nothing to test on the environment
  - "test/.*"  # Guess
  - "src/clj/memento/core.clj" # Mostly start/stop code which the tests don't touch
  - "src/clj/memento/routes/home.clj" # Home page routes that the tests don't currently touch
  - "src/cljs" # Otherwise a patch that alters only ClojureScript code would fail because of low coverage